### ISSUE TITLE
valueBox icons not big

### ISSUE THREAD

**Issue by petzi53** [rstudio/rmarkdown-book#22] opened 2018-06-24 07:25 UTC
Trying your example file `04-valueboxes.Rmd`  my awesome icons are very small and at the left bottom corner of the box. Not sure if I missed something (some css styling?) or there is something wrong. 

[The recommended change in css styles (e.g. [W3schools](https://www.w3schools.com/icons/fontawesome_icons_intro.asp) or [StackOverflow](https://stackoverflow.com/questions/31992235/how-do-i-decrease-the-size-of-a-font-awesome-icon) did not work for me (or I did not know where and how to apply them in the example code.]
<hr />
I am using rmarkdown version 1.10, pandoc version  1.19.2.1 and RStudio Version 1.1.453 on a macOS 10.13.5.

**Comment by yihui** [comment] 2018-06-25 03:40
Duplicate of https://github.com/rstudio/flexdashboard/issues/189

**Closed** 2018-06-27 04:47 UTC
